apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ktxv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ktxv
    app.kubernetes.io/part-of: byoc-app-vugi
  name: ktxv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: ktxv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: ktxv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-hhra-tenant/byoc-app-vugi/ktxv@sha256:4e96e141664b53122b699ac1fa0164e200bfc2a073e387ac7dc221a5427fb801
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
