apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ktxv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ktxv
    app.kubernetes.io/part-of: byoc-app-vugi
  name: ktxv
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: ktxv
status:
  loadBalancer: {}
