apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ktxv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ktxv
    app.kubernetes.io/part-of: byoc-app-vugi
  name: ktxv
spec:
  rules:
  - host: ktxv-byoc-hhra-tenant.apps.b4526e4185b68725c87f.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: ktxv
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
